const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const bestiary = [
  {
    name: "Lacerte",
    type: "Créature",
    menace: "Mineure",
    experience: "Débutant",
    role: "Mineur",
    attaque: "3D",
    contact: "7",
    action: "3D",
    specialite: "4D",
    specialite_details: "Escalade",
    relances: "0D",
    reserve: "0D",
    reaction: "3D",
    arme: "morsure, griffes, dommages 1",
    armure: "peau épaisse, protection 1",
    blessuresLegeres: 1,
    blessuresGraves: 1,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 1,
    seuilBlessuresGraves: 4,
    seuilBlessuresMortelles: 6,
    capacites: "S'efforcent de tuer un des PJ en particulier; se replient si Blessure Grave."
  }, //[cite: 1]
  {
    name: "Villageois de Marad standard",
    type: "Humanoïde",
    menace: "Mineure",
    experience: "Débutant",
    role: "Mineur",
    attaque: "3D",
    contact: "7",
    action: "3D",
    specialite: "4D",
    specialite_details: "En fonction du métier",
    relances: "0",
    reserve: "0",
    reaction: "3D",
    arme: "aucune",
    armure: "aucune",
    blessuresLegeres: 1,
    blessuresGraves: 1,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 1,
    seuilBlessuresGraves: 4,
    seuilBlessuresMortelles: 6,
    capacites: ""
  }, //[cite: 1]
  {
    name: "Villageois de Marad (compétiteur)",
    type: "Humanoïde",
    menace: "Sérieuse",
    experience: "Confirmé",
    role: "Secondaire",
    attaque: "4D",
    contact: "7",
    action: "3D",
    specialite: "5D",
    specialite_details: "S'applique aux épreuves",
    relances: "0D",
    reserve: "1D",
    reaction: "3D+1",
    arme: "couteau, dommages 2",
    armure: "aucune",
    blessuresLegeres: 2,
    blessuresGraves: 1,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 2,
    seuilBlessuresGraves: 5,
    seuilBlessuresMortelles: 8,
    capacites: ""
  }, //[cite: 1]
  {
    name: "Soldat du Culte",
    type: "Humanoïde",
    menace: "Sérieuse",
    experience: "Confirmé",
    role: "Mineur",
    attaque: "4D",
    contact: "7",
    action: "3D",
    specialite: "5D",
    specialite_details: "",
    relances: "0D",
    reserve: "0D",
    reaction: "3D",
    arme: "glaive, dommages 2",
    armure: "cuirasse, protection 2",
    blessuresLegeres: 2,
    blessuresGraves: 1,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 2,
    seuilBlessuresGraves: 5,
    seuilBlessuresMortelles: 9,
    capacites: ""
  }, //[cite: 1]
  {
    name: "Hershaad",
    type: "Humanoïde",
    menace: "Sérieuse",
    experience: "Confirmé",
    role: "Secondaire",
    attaque: "5D",
    contact: "7",
    action: "3D",
    specialite: "5D",
    specialite_details: "Commandement",
    relances: "1D",
    reserve: "1D",
    reaction: "3D+1",
    arme: "glaive, dommages 3",
    armure: "cuirasse renforcée, protection 3, Lourd (2)",
    blessuresLegeres: 2,
    blessuresGraves: 2,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 2,
    seuilBlessuresGraves: 5,
    seuilBlessuresMortelles: 9,
    capacites: ""
  }, //[cite: 1]
  {
    name: "Soldat du capitaine Radec",
    type: "Humanoïde",
    menace: "Sérieuse",
    experience: "Confirmé",
    role: "Mineur",
    attaque: "4D",
    contact: "7",
    action: "3D",
    specialite: "5D",
    specialite_details: "Commandement",
    relances: "0D",
    reserve: "0D",
    reaction: "3D",
    arme: "épée, dommages 2",
    armure: "cuir, protection 1",
    blessuresLegeres: 2,
    blessuresGraves: 1,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 2,
    seuilBlessuresGraves: 5,
    seuilBlessuresMortelles: 9,
    capacites: ""
  }, //[cite: 1]
  {
    name: "Capitaine Radec",
    type: "Humanoïde",
    menace: "Majeure",
    experience: "Expert",
    role: "Important",
    attaque: "5D",
    contact: "7",
    action: "4D",
    specialite: "6D",
    specialite_details: "Commandement",
    relances: "1D",
    reserve: "2D",
    reaction: "3D+2",
    arme: "épée, dommages 3",
    armure: "cuir renforcé, protection 2",
    blessuresLegeres: 2,
    blessuresGraves: 2,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 2,
    seuilBlessuresGraves: 5,
    seuilBlessuresMortelles: 9,
    capacites: ""
  }, //[cite: 1]
  {
    name: "Descendant d'Hursagide",
    type: "Humanoïde",
    menace: "Mortelle",
    experience: "Expert",
    role: "Secondaire",
    attaque: "6D",
    contact: "7",
    action: "4D",
    specialite: "6D",
    specialite_details: "Survie",
    relances: "1D",
    reserve: "1D",
    reaction: "3D+1",
    arme: "épée double, dommages 4, Rapide (2)",
    armure: "cuir renforcé et peau épaisse, protection 3",
    blessuresLegeres: 2,
    blessuresGraves: 2,
    blessuresMortelles: 2,
    seuilBlessuresLegeres: 3,
    seuilBlessuresGraves: 6,
    seuilBlessuresMortelles: 9,
    capacites: ""
  }, //[cite: 1]
  {
    name: "Grande araignée (mygale)",
    type: "Arachnide",
    menace: "",
    experience: "",
    role: "",
    attaque: "3D",
    contact: "5/7",
    action: "2D",
    specialite: "4D",
    specialite_details: "Discrétion, Vigilance, grimper",
    relances: "1D",
    reserve: "0D",
    reaction: "3D",
    arme: "chélicère, dommages 1 (P)",
    armure: "aucune",
    blessuresLegeres: 0,
    blessuresGraves: 1,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 0,
    seuilBlessuresGraves: 2,
    seuilBlessuresMortelles: 4,
    capacites: "Morsure nécrosante"
  }, //[cite: 2]
  {
    name: "Petite araignée (veuve noire)",
    type: "Arachnide",
    menace: "",
    experience: "",
    role: "",
    attaque: "3D",
    contact: "7",
    action: "2D",
    specialite: "4D",
    specialite_details: "Discrétion, Vigilance, grimper",
    relances: "0D",
    reserve: "1D",
    reaction: "3D",
    arme: "chélicère, dommages 1 (P)",
    armure: "aucune",
    blessuresLegeres: 0,
    blessuresGraves: 0,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 0,
    seuilBlessuresGraves: 0,
    seuilBlessuresMortelles: 2,
    capacites: "Venin: Virulence 8 (Virulence 9 pour la veuve écarlate)"
  }, //[cite: 2]
  {
    name: "Araignée géante",
    type: "Bête extraordinaire",
    menace: "",
    experience: "",
    role: "",
    attaque: "5D",
    contact: "5/7",
    action: "3D",
    specialite: "5D",
    specialite_details: "Discrétion, Vigilance, escalade",
    relances: "1D",
    reserve: "1D",
    reaction: "3D+1",
    arme: "chélicère, dommages 3 (P)",
    armure: "carapace, partielle 2",
    blessuresLegeres: 2,
    blessuresGraves: 2,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 2,
    seuilBlessuresGraves: 5,
    seuilBlessuresMortelles: 9,
    capacites: "Territoriale, Toile, Venin (Virulence 5)"
  }, //[cite: 2]
  {
    name: "Scorpion géant",
    type: "Bête extraordinaire",
    menace: "",
    experience: "",
    role: "",
    attaque: "5D",
    contact: "5/7",
    action: "4D",
    specialite: "5D",
    specialite_details: "Discrétion, Vigilance, course",
    relances: "1D",
    reserve: "1D",
    reaction: "3D+1",
    arme: "pinces, dommages 3 (T), Rapide (2); aiguillon, dommages 4 (P)",
    armure: "carapace, intégrale 3",
    blessuresLegeres: 2,
    blessuresGraves: 3,
    blessuresMortelles: 2,
    seuilBlessuresLegeres: 3,
    seuilBlessuresGraves: 6,
    seuilBlessuresMortelles: 9,
    capacites: "Venin (Virulence 6)"
  }, //[cite: 2]
  {
    name: "Scorpion",
    type: "Arachnide",
    menace: "",
    experience: "",
    role: "",
    attaque: "3D",
    contact: "7",
    action: "3D",
    specialite: "4D",
    specialite_details: "Discrétion, Vigilance",
    relances: "0D",
    reserve: "0D",
    reaction: "3D",
    arme: "aiguillon, dommages 1 (P)",
    armure: "aucune",
    blessuresLegeres: 0,
    blessuresGraves: 1,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 0,
    seuilBlessuresGraves: 2,
    seuilBlessuresMortelles: 5,
    capacites: "Venin (Gros: Virulence 4 ou 5, Petits: Virulence 6 à 8)"
  }, //[cite: 2]
  {
    name: "Molosse",
    type: "Canidé",
    menace: "",
    experience: "",
    role: "",
    attaque: "4D",
    contact: "5/7",
    action: "3D",
    specialite: "4D",
    specialite_details: "Pistage, course",
    relances: "1D",
    reserve: "1D",
    reaction: "3D+1",
    arme: "crocs, dommages 3 (P)",
    armure: "aucune",
    blessuresLegeres: 2,
    blessuresGraves: 2,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 3,
    seuilBlessuresGraves: 6,
    seuilBlessuresMortelles: 9,
    capacites: ""
  }, //[cite: 2]
  {
    name: "Loup",
    type: "Canidé",
    menace: "",
    experience: "",
    role: "",
    attaque: "3D",
    contact: "5/7",
    action: "3D",
    specialite: "4D",
    specialite_details: "Pistage, course",
    relances: "0D",
    reserve: "0D",
    reaction: "3D",
    arme: "crocs, dommages 2 (P)",
    armure: "aucune",
    blessuresLegeres: 2,
    blessuresGraves: 1,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 2,
    seuilBlessuresGraves: 5,
    seuilBlessuresMortelles: 8,
    capacites: ""
  }, //[cite: 2]
  {
    name: "Chien",
    type: "Canidé",
    menace: "",
    experience: "",
    role: "",
    attaque: "4D",
    contact: "5/7",
    action: "3D",
    specialite: "4D",
    specialite_details: "Pistage, course",
    relances: "1D",
    reserve: "0D",
    reaction: "3D",
    arme: "crocs, dommages 3 (P)",
    armure: "aucune",
    blessuresLegeres: 2,
    blessuresGraves: 2,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 2,
    seuilBlessuresGraves: 5,
    seuilBlessuresMortelles: 8,
    capacites: ""
  }, //[cite: 2]
  {
    name: "Loup Géant",
    type: "Bête extraordinaire",
    menace: "",
    experience: "",
    role: "",
    attaque: "6D",
    contact: "5/7",
    action: "4D",
    specialite: "6D",
    specialite_details: "Pistage, course",
    relances: "2D",
    reserve: "1D",
    reaction: "3D+1",
    arme: "crocs, dommages 5 (P)",
    armure: "fourrure épaisse, intégrale 1",
    blessuresLegeres: 3,
    blessuresGraves: 2,
    blessuresMortelles: 2,
    seuilBlessuresLegeres: 3,
    seuilBlessuresGraves: 6,
    seuilBlessuresMortelles: 9,
    capacites: "Solitaires ou en couple"
  }, //[cite: 2]
  {
    name: "Cheval léger (coursier)",
    type: "Cheval",
    menace: "",
    experience: "",
    role: "",
    attaque: "4D",
    contact: "7",
    action: "3D",
    specialite: "5D",
    specialite_details: "course",
    relances: "1D",
    reserve: "0D",
    reaction: "3D",
    arme: "sabots, dommages 2 (C)",
    armure: "aucune",
    blessuresLegeres: 2,
    blessuresGraves: 2,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 3,
    seuilBlessuresGraves: 6,
    seuilBlessuresMortelles: 9,
    capacites: "Ruade: si attaque derrière, dommages 4."
  }, //[cite: 2]
  {
    name: "Cheval lourd (cheval de bât, destrier)",
    type: "Cheval",
    menace: "",
    experience: "",
    role: "",
    attaque: "5D",
    contact: "5/7",
    action: "3D",
    specialite: "4D",
    specialite_details: "course",
    relances: "1D",
    reserve: "1D",
    reaction: "3D",
    arme: "sabots, dommages 3 (C)",
    armure: "aucune",
    blessuresLegeres: 3,
    blessuresGraves: 2,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 3,
    seuilBlessuresGraves: 6,
    seuilBlessuresMortelles: 10,
    capacites: "Ruade: si attaque derrière, dommages 5."
  }, //[cite: 2]
  {
    name: "Grand tigre à dents de sabre",
    type: "Bête extraordinaire",
    menace: "",
    experience: "",
    role: "",
    attaque: "6D",
    contact: "5/7",
    action: "4D",
    specialite: "6D",
    specialite_details: "Discrétion, Pistage des proies, course",
    relances: "2D",
    reserve: "2D",
    reaction: "3D+1",
    arme: "griffes, dommages 4 (T); crocs, dommages 4 (P)",
    armure: "peau épaisse, intégrale 1",
    blessuresLegeres: 2,
    blessuresGraves: 3,
    blessuresMortelles: 2,
    seuilBlessuresLegeres: 3,
    seuilBlessuresGraves: 6,
    seuilBlessuresMortelles: 10,
    capacites: "Bond du prédateur, Puissance du prédateur"
  }, //[cite: 2]
  {
    name: "Grand félin commun (lion, tigre, panthère)",
    type: "Grand félin",
    menace: "",
    experience: "",
    role: "",
    attaque: "5D",
    contact: "5/7",
    action: "3D",
    specialite: "4D",
    specialite_details: "Discrétion, Pistage des proies, course",
    relances: "1D",
    reserve: "1D",
    reaction: "3D+1",
    arme: "griffes, dommages 3 (T); crocs, dommages 3 (P)",
    armure: "aucune",
    blessuresLegeres: 2,
    blessuresGraves: 2,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 2,
    seuilBlessuresGraves: 5,
    seuilBlessuresMortelles: 9,
    capacites: "Bond du prédateur"
  }, //[cite: 2]
  {
    name: "Belette",
    type: "Petit mammifère",
    menace: "",
    experience: "",
    role: "",
    attaque: "2D",
    contact: "7",
    action: "2D",
    specialite: "3D",
    specialite_details: "Discrétion, grimper, fuite",
    relances: "0D",
    reserve: "0D",
    reaction: "3D",
    arme: "crocs, dommages 2 (P)",
    armure: "aucune",
    blessuresLegeres: 1,
    blessuresGraves: 1,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 2,
    seuilBlessuresGraves: 4,
    seuilBlessuresMortelles: 6,
    capacites: ""
  }, //[cite: 2]
  {
    name: "Chauve-souris",
    type: "Petit mammifère",
    menace: "",
    experience: "",
    role: "",
    attaque: "2D",
    contact: "7",
    action: "2D",
    specialite: "4D",
    specialite_details: "Vigilance, escalade, vol",
    relances: "0D",
    reserve: "0D",
    reaction: "3D",
    arme: "crocs, dommages 1 (P)",
    armure: "aucune",
    blessuresLegeres: 1,
    blessuresGraves: 1,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 1,
    seuilBlessuresGraves: 3,
    seuilBlessuresMortelles: 5,
    capacites: "Nyctalope (aucun malus dans l'obscurité)"
  }, //[cite: 2]
  {
    name: "Chat",
    type: "Petit mammifère",
    menace: "",
    experience: "",
    role: "",
    attaque: "3D",
    contact: "7",
    action: "3D",
    specialite: "4D",
    specialite_details: "Discrétion, Vigilance, fuite",
    relances: "1D",
    reserve: "0D",
    reaction: "3D+1",
    arme: "crocs, dommages 2 (P); griffes, dommages 1 (T)",
    armure: "aucune",
    blessuresLegeres: 1,
    blessuresGraves: 1,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 2,
    seuilBlessuresGraves: 4,
    seuilBlessuresMortelles: 6,
    capacites: ""
  }, //[cite: 2]
  {
    name: "Lièvre",
    type: "Petit mammifère",
    menace: "",
    experience: "",
    role: "",
    attaque: "2D",
    contact: "7",
    action: "2D",
    specialite: "4D",
    specialite_details: "Discrétion, fuite",
    relances: "0D",
    reserve: "0D",
    reaction: "3D+1",
    arme: "dents, dommages 1 (P)",
    armure: "aucune",
    blessuresLegeres: 1,
    blessuresGraves: 1,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 1,
    seuilBlessuresGraves: 3,
    seuilBlessuresMortelles: 5,
    capacites: ""
  }, //[cite: 2]
  {
    name: "Rat",
    type: "Petit mammifère",
    menace: "",
    experience: "",
    role: "",
    attaque: "2D",
    contact: "7",
    action: "2D",
    specialite: "4D",
    specialite_details: "Discrétion, fuite",
    relances: "0D",
    reserve: "0D",
    reaction: "3D",
    arme: "dents, dommages 1 (P)",
    armure: "aucune",
    blessuresLegeres: 1,
    blessuresGraves: 1,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 1,
    seuilBlessuresGraves: 2,
    seuilBlessuresMortelles: 4,
    capacites: ""
  }, //[cite: 2]
  {
    name: "Rat géant",
    type: "Bête extraordinaire",
    menace: "",
    experience: "",
    role: "",
    attaque: "4D",
    contact: "5/7",
    action: "3D",
    specialite: "5D",
    specialite_details: "Vigilance, fuite",
    relances: "1D",
    reserve: "0D",
    reaction: "3D+1",
    arme: "dents, dommages 3 (P)",
    armure: "aucune",
    blessuresLegeres: 2,
    blessuresGraves: 1,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 2,
    seuilBlessuresGraves: 5,
    seuilBlessuresMortelles: 8,
    capacites: "Vivent en nichée"
  }, //[cite: 2]
  {
    name: "Cerf",
    type: "Grand mammifère",
    menace: "",
    experience: "",
    role: "",
    attaque: "4D",
    contact: "5/7",
    action: "3D",
    specialite: "5D",
    specialite_details: "Vigilance, fuite",
    relances: "0D",
    reserve: "1D",
    reaction: "3D+1",
    arme: "bois, dommages 3 (P)",
    armure: "aucune",
    blessuresLegeres: 2,
    blessuresGraves: 2,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 3,
    seuilBlessuresGraves: 5,
    seuilBlessuresMortelles: 9,
    capacites: ""
  }, //[cite: 2]
  {
    name: "Mégacéros",
    type: "Bête extraordinaire",
    menace: "",
    experience: "",
    role: "",
    attaque: "5D",
    contact: "5/7",
    action: "3D",
    specialite: "5D",
    specialite_details: "Discrétion, grimper",
    relances: "1D",
    reserve: "1D",
    reaction: "3D+1",
    arme: "bois, dommages 4 (P)",
    armure: "peau épaisse, intégrale 1",
    blessuresLegeres: 3,
    blessuresGraves: 3,
    blessuresMortelles: 2,
    seuilBlessuresLegeres: 3,
    seuilBlessuresGraves: 6,
    seuilBlessuresMortelles: 9,
    capacites: ""
  }, //[cite: 2]
  {
    name: "Dromadaire",
    type: "Grand mammifère",
    menace: "",
    experience: "",
    role: "",
    attaque: "3D",
    contact: "7",
    action: "3D",
    specialite: "4D",
    specialite_details: "course, fuite",
    relances: "0D",
    reserve: "0D",
    reaction: "3D",
    arme: "dents, dommages 1 (T)",
    armure: "aucune",
    blessuresLegeres: 2,
    blessuresGraves: 2,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 3,
    seuilBlessuresGraves: 6,
    seuilBlessuresMortelles: 9,
    capacites: ""
  }, //[cite: 2]
  {
    name: "Éléphant",
    type: "Grand mammifère",
    menace: "",
    experience: "",
    role: "",
    attaque: "6D",
    contact: "5/7",
    action: "3D",
    specialite: "5D",
    specialite_details: "Vigilance, course",
    relances: "1D",
    reserve: "2D",
    reaction: "3D",
    arme: "défenses, dommages 4 (P)",
    armure: "peau épaisse, intégrale 2",
    blessuresLegeres: 4,
    blessuresGraves: 3,
    blessuresMortelles: 2,
    seuilBlessuresLegeres: 4,
    seuilBlessuresGraves: 7,
    seuilBlessuresMortelles: 10,
    capacites: "Charge (+1D)"
  }, //[cite: 2]
  {
    name: "Mammut'h géant",
    type: "Bête extraordinaire",
    menace: "",
    experience: "",
    role: "",
    attaque: "7D",
    contact: "5/7",
    action: "3D",
    specialite: "4D",
    specialite_details: "course",
    relances: "1D",
    reserve: "2D",
    reaction: "3D",
    arme: "défenses, dommages 7 (P)",
    armure: "peau épaisse, intégrale 4",
    blessuresLegeres: 5,
    blessuresGraves: 4,
    blessuresMortelles: 2,
    seuilBlessuresLegeres: 5,
    seuilBlessuresGraves: 8,
    seuilBlessuresMortelles: 12,
    capacites: "Charge (+2D, 3 cibles)"
  }, //[cite: 2]
  {
    name: "Hippopotame",
    type: "Grand mammifère",
    menace: "",
    experience: "",
    role: "",
    attaque: "5D",
    contact: "5/7",
    action: "3D",
    specialite: "4D",
    specialite_details: "Vigilance, course, nage",
    relances: "1D",
    reserve: "1D",
    reaction: "3D",
    arme: "dents, dommages 4 (P)",
    armure: "peau épaisse, intégrale 1",
    blessuresLegeres: 3,
    blessuresGraves: 2,
    blessuresMortelles: 2,
    seuilBlessuresLegeres: 3,
    seuilBlessuresGraves: 6,
    seuilBlessuresMortelles: 10,
    capacites: "Charge (+2D, piétine)"
  }, //[cite: 2]
  {
    name: "Ours",
    type: "Grand mammifère",
    menace: "",
    experience: "",
    role: "",
    attaque: "5D",
    contact: "5/7",
    action: "3D",
    specialite: "4D",
    specialite_details: "Pistage, course, escalader",
    relances: "1D",
    reserve: "1D",
    reaction: "3D",
    arme: "crocs, dommages 4 (P); griffes, dommages 3 (T)",
    armure: "fourrure épaisse, intégrale 1",
    blessuresLegeres: 2,
    blessuresGraves: 3,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 3,
    seuilBlessuresGraves: 6,
    seuilBlessuresMortelles: 9,
    capacites: ""
  }, //[cite: 2]
  {
    name: "Ours des cavernes",
    type: "Bête extraordinaire",
    menace: "",
    experience: "",
    role: "",
    attaque: "6D",
    contact: "5/7",
    action: "3D",
    specialite: "4D",
    specialite_details: "Pistage, course",
    relances: "1D",
    reserve: "2D",
    reaction: "3D",
    arme: "crocs, dommages 5 (P); griffes, dommages 4 (T)",
    armure: "peau épaisse, intégrale 2",
    blessuresLegeres: 4,
    blessuresGraves: 3,
    blessuresMortelles: 2,
    seuilBlessuresLegeres: 4,
    seuilBlessuresGraves: 7,
    seuilBlessuresMortelles: 10,
    capacites: ""
  }, //[cite: 2]
  {
    name: "Rhinocéros",
    type: "Grand mammifère",
    menace: "",
    experience: "",
    role: "",
    attaque: "5D",
    contact: "5/7",
    action: "3D",
    specialite: "5D",
    specialite_details: "course",
    relances: "1D",
    reserve: "2D",
    reaction: "3D",
    arme: "corne, dommages 5 (P)",
    armure: "peau épaisse, intégrale 3",
    blessuresLegeres: 3,
    blessuresGraves: 3,
    blessuresMortelles: 2,
    seuilBlessuresLegeres: 4,
    seuilBlessuresGraves: 7,
    seuilBlessuresMortelles: 10,
    capacites: "Charge (+2D)"
  }, //[cite: 2]
  {
    name: "Sanglier",
    type: "Grand mammifère",
    menace: "",
    experience: "",
    role: "",
    attaque: "4D",
    contact: "5/7",
    action: "3D",
    specialite: "4D",
    specialite_details: "course",
    relances: "1D",
    reserve: "0D",
    reaction: "3D",
    arme: "défenses, dommages 3 (T)",
    armure: "peau épaisse, intégrale 1",
    blessuresLegeres: 2,
    blessuresGraves: 2,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 3,
    seuilBlessuresGraves: 6,
    seuilBlessuresMortelles: 9,
    capacites: "Charge (+1D)"
  }, //[cite: 2]
  {
    name: "Sanglier géant",
    type: "Bête extraordinaire",
    menace: "",
    experience: "",
    role: "",
    attaque: "5D",
    contact: "5/7",
    action: "4D",
    specialite: "5D",
    specialite_details: "course",
    relances: "2D",
    reserve: "1D",
    reaction: "3D+1",
    arme: "défenses, dommages 4 (T)",
    armure: "peau épaisse, intégrale 2",
    blessuresLegeres: 3,
    blessuresGraves: 3,
    blessuresMortelles: 2,
    seuilBlessuresLegeres: 3,
    seuilBlessuresGraves: 6,
    seuilBlessuresMortelles: 10,
    capacites: "Charge (+2D), Frénésie"
  }, //[cite: 2]
  {
    name: "Taureau",
    type: "Grand mammifère",
    menace: "",
    experience: "",
    role: "",
    attaque: "4D",
    contact: "5/7",
    action: "3D",
    specialite: "4D",
    specialite_details: "course",
    relances: "1D",
    reserve: "1D",
    reaction: "3D",
    arme: "cornes, dommages 3 (P)",
    armure: "aucune",
    blessuresLegeres: 3,
    blessuresGraves: 2,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 3,
    seuilBlessuresGraves: 6,
    seuilBlessuresMortelles: 9,
    capacites: "Charge (+1D)"
  }, //[cite: 2]
  {
    name: "Grand taurus",
    type: "Bête extraordinaire",
    menace: "",
    experience: "",
    role: "",
    attaque: "6D",
    contact: "5/7",
    action: "3D",
    specialite: "4D",
    specialite_details: "course",
    relances: "2D",
    reserve: "2D",
    reaction: "3D+1",
    arme: "cornes, dommages 5 (P)",
    armure: "peau épaisse, intégrale 1",
    blessuresLegeres: 4,
    blessuresGraves: 3,
    blessuresMortelles: 2,
    seuilBlessuresLegeres: 4,
    seuilBlessuresGraves: 8,
    seuilBlessuresMortelles: 11,
    capacites: "Charge (+2D)"
  }, //[cite: 2]
  {
    name: "Rapace (aigle, grand faucon, chouette)",
    type: "Oiseau",
    menace: "",
    experience: "",
    role: "",
    attaque: "4D",
    contact: "7",
    action: "2D",
    specialite: "3D",
    specialite_details: "Vigilance, vol",
    relances: "0D",
    reserve: "0D",
    reaction: "3D",
    arme: "serres, dommages 1 (T); bec, dommages 1 (P)",
    armure: "aucune",
    blessuresLegeres: 2,
    blessuresGraves: 1,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 2,
    seuilBlessuresGraves: 4,
    seuilBlessuresMortelles: 6,
    capacites: "Attaque en piqué (+1D)"
  }, //[cite: 2]
  {
    name: "Aigle géant",
    type: "Bête extraordinaire",
    menace: "",
    experience: "",
    role: "",
    attaque: "6D",
    contact: "5/7",
    action: "3D",
    specialite: "4D",
    specialite_details: "Vigilance, vol",
    relances: "1D",
    reserve: "2D",
    reaction: "3D",
    arme: "serres, dommages 3 (T); bec, dommages 3 (P)",
    armure: "aucune",
    blessuresLegeres: 2,
    blessuresGraves: 2,
    blessuresMortelles: 1,
    seuilBlessuresLegeres: 3,
    seuilBlessuresGraves: 6,
    seuilBlessuresMortelles: 10,
    capacites: "Attaque en piqué (+2D)"
  } //[cite: 2]
];

async function main() {
  console.log("Début de l'insertion des fixtures pour le Bestiaire...");
  
  for (const b of bestiary) {
    const exists = await prisma.adversary.findFirst({
      where: { name: b.name }
    });

    if (!exists) {
      await prisma.adversary.create({
        data: b
      });
      console.log(`[+] Ajouté: ${b.name}`);
    } else {
      console.log(`[=] Existe déjà: ${b.name}`);
    }
  }
  
  console.log("Sauvegarde des fixtures terminée !");
}

main()
  .catch(e => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
