FROM node:22-alpine

RUN apk add --no-cache \
    build-base \
    python3 \
    py3-pip \
    openssl

WORKDIR /app

COPY package*.json ./

RUN npm install --legacy-peer-deps

ENV NODE_ENV=development

COPY . .

RUN npx prisma generate --schema=/app/app/prisma/schema.prisma

EXPOSE 3000

CMD ["npm", "start"]